### ISSUE TITLE
Updated greyhole on ubuntu 16.04. Errors on run

### ISSUE THREAD

**Issue by Burden50** [gboudreau/Greyhole#171]
```
Feb 24 12:36:45 ERROR initialize: PHP Fatal Error: Uncaught Exception: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xCB' for column 'full_path' at row 83 in /usr/bin/greyhole:619
Stack trace:
#0 /usr/bin/greyhole(900): DB::execute('ALTER TABLE `ta...')
#1 /usr/bin/greyhole(699): DB::migrate_11_varchar()
#2 /usr/bin/greyhole(600): DB::migrate()
#3 /usr/bin/greyhole(3411): DB::connect(false)
#4 /usr/bin/greyhole(3373): CommandLineHelper->getRunner()
#5 /usr/bin/greyhole(3607): CommandLineHelper->processCommandLine()
#6 {main}
  thrown; BT: greyhole[L619]
```

**Comment by gboudreau** [comment]
Could you your this in MySQL, and paste here what you get?

    DESCRIBE TABLE tasks_completed;

**Comment by Burden50** [comment]
```
mysql> DESCRIBE tasks_completed;
+-----------------+-----------------------------------------------------+------+-----+-------------------+-------+
| Field           | Type                                                | Null | Key | Default           | Extra |
+-----------------+-----------------------------------------------------+------+-----+-------------------+-------+
| id              | bigint(20) unsigned                                 | NO   |     | NULL              |       |
| action          | varchar(10)                                         | NO   |     | NULL              |       |
| share           | tinytext                                            | NO   |     | NULL              |       |
| full_path       | tinytext                                            | YES  |     | NULL              |       |
| additional_info | tinytext                                            | YES  |     | NULL              |       |
| complete        | enum('yes','no','frozen','thawed','idle','written') | NO   |     | NULL              |       |
| event_date      | timestamp                                           | NO   |     | CURRENT_TIMESTAMP |       |
+-----------------+-----------------------------------------------------+------+-----+-------------------+-------+
7 rows in set (0.17 sec)
```

**Comment by gboudreau** [comment]
SELECT * FROM information_schema.`TABLES` T,
        information_schema.`COLLATION_CHARACTER_SET_APPLICABILITY` CCSA
        WHERE CCSA.collation_name = T.table_collation
        AND T.table_schema = "greyhole"
        AND T.table_name = "tasks_completed" \G

**Comment by Burden50** [comment]
```
mysql> SELECT * FROM information_schema.`TABLES` T,     information_schema.`COLLATION_CHARACTER_SET_APPLICABILITY` CCSA     WHERE CCSA.collation_name = T.table_collation     AND T.table_schema = "service_greyhole"     AND T.table_name = "tasks_completed"\G
*************************** 1. row ***************************
     TABLE_CATALOG: def
      TABLE_SCHEMA: service_greyhole
        TABLE_NAME: tasks_completed
        TABLE_TYPE: BASE TABLE
            ENGINE: MyISAM
           VERSION: 10
        ROW_FORMAT: Dynamic
        TABLE_ROWS: 6595970
    AVG_ROW_LENGTH: 148
       DATA_LENGTH: 1877319332
   MAX_DATA_LENGTH: 281474976710655
      INDEX_LENGTH: 1024
         DATA_FREE: 894683196
    AUTO_INCREMENT: NULL
       CREATE_TIME: 2016-10-25 16:32:59
       UPDATE_TIME: 2017-02-24 06:25:04
        CHECK_TIME: 2017-01-28 06:29:20
   TABLE_COLLATION: utf8_general_ci
          CHECKSUM: NULL
    CREATE_OPTIONS:
     TABLE_COMMENT:
    COLLATION_NAME: utf8_general_ci
CHARACTER_SET_NAME: utf8
1 row in set (0.02 sec)
```
